/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Bomberman.PartidaClient;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author angelfabricio
 */
public class ConectarCliente extends javax.swing.JFrame {
    
    String IPaddress;
    int puerto;
    char ColorPj = '1';
    String nickname;
    
    
    /**
     * Creates new form ConectarCliente
     */
    public ConectarCliente() {
        initComponents();
        
        BotonConectarse.addActionListener ( new ConectarseButtonAction());
        ColorBombermanCombo.addActionListener ( new ColorComboBoxAction());

        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IPTextField = new javax.swing.JTextField();
        PuertoTextField = new javax.swing.JTextField();
        ColorBombermanCombo = new javax.swing.JComboBox();
        BotonConectarse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nicknameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Conectarse a Partida");

        jLabel2.setText("Direccion IP:");

        jLabel3.setText("Puerto:");

        jLabel4.setText("Color de tu Bomberman:");

        IPTextField.setText("LocalHost");
        IPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPTextFieldActionPerformed(evt);
            }
        });

        PuertoTextField.setText("208");
        PuertoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuertoTextFieldActionPerformed(evt);
            }
        });

        ColorBombermanCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blanco", "Negro", "Azul", "Verde", "Rojo", "Vintage" }));
        ColorBombermanCombo.setSelectedItem('1');

        BotonConectarse.setText("Conectarse a Host");

        jLabel5.setText("NickName:");

        nicknameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IPTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(PuertoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ColorBombermanCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicknameTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(BotonConectarse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PuertoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ColorBombermanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BotonConectarse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PuertoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuertoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuertoTextFieldActionPerformed

    private void IPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTextFieldActionPerformed

    private void nicknameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameTextFieldActionPerformed
    
    //---------------------Listeners-------------------------------------------------------
        public class ConectarseButtonAction implements ActionListener{
            @Override
        public void actionPerformed(ActionEvent e) {
            
            puerto = Integer.parseInt(PuertoTextField.getText());
            IPaddress = IPTextField.getText();
            nickname = nicknameTextField.getText();
            
            PartidaClient partida = new PartidaClient( puerto, IPaddress, nickname, ColorPj);
            partida.inicializar();
            Thread hilo = new Thread ( partida );
            
                try { hilo.start(); }
                catch (Exception ex) { }
                
            dispose();    
        }
    } 
    public class ColorComboBoxAction implements ActionListener{
            @Override
        public void actionPerformed(ActionEvent e) {
               
               String s = (String) ColorBombermanCombo.getSelectedItem();
               
              switch ( s ){
                  
                  case "Blanco":{
                      ColorPj = '1';
                      break;
                  }
                  
                  case "Negro":{
                      ColorPj = '2';
                      break;
                  }    
                  case "Azul":{
                      ColorPj = '3';
                      break;
                  }
                  case "Verde":{
                      ColorPj = '4';
                      break;
                  }
                  
                  case "Rojo":{
                      ColorPj = '5';
                      break;
                  }    
                  case "Vintage":{
                      ColorPj = '6';
                      break;
                  }
              }
              
                       
        }
    } 
    //---------------------Listeners-------------------------------------------------------
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConectarse;
    private javax.swing.JComboBox ColorBombermanCombo;
    private javax.swing.JTextField IPTextField;
    private javax.swing.JTextField PuertoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nicknameTextField;
    // End of variables declaration//GEN-END:variables
}
