/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Bomberman.PartidaHost;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.InetAddress;
import java.net.UnknownHostException;


/**
 *
 * @author angelfabricio
 */
public class VentanaHost extends javax.swing.JFrame {
    String IPaddress;
    
    String NickName;
    int puerto;
    char ColorMapa = '1', ColorPj = '1';
    
    /**
     * Creates new form IniciarServidor
     * @param Host
     */
    public VentanaHost() {
        initComponents();
        
        BotonIniciarHost.addActionListener ( new IniciarHostButtonAction());
        ColorMapaCombo.addActionListener ( new ColorMapaComboBoxAction());
        ColorPjCombo.addActionListener ( new ColorPjComboBoxAction());

        
        try {IPaddress = InetAddress.getLocalHost().getHostAddress();} 
        catch (UnknownHostException ex) {}
        this.IPlabel.setText("Direccion IP:   " + IPaddress);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox3 = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IPlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PuertoTextField = new javax.swing.JTextField();
        ColorMapaCombo = new javax.swing.JComboBox();
        BotonIniciarHost = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ColorPjCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        nicknameTextField = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("   Crear Nueva Sala");

        IPlabel.setText("Direccion IP:");

        jLabel3.setText("Puerto:");

        jLabel4.setText("Color Mapa:");

        PuertoTextField.setText("208");
        PuertoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuertoTextFieldActionPerformed(evt);
            }
        });

        ColorMapaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Verde", "Azul", "Rojo", "Amarillo" }));
        ColorMapaCombo.setSelectedItem('1');

        BotonIniciarHost.setText("Empezar Partida");
        BotonIniciarHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarHostActionPerformed(evt);
            }
        });

        jLabel2.setText("Color de tu Bomberman:");

        ColorPjCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blanco", "Negro", "Azul", "Verde", "Rojo", "Vintage" }));
        ColorPjCombo.setSelectedItem('1');

        jLabel5.setText("NickName:");

        nicknameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(105, 105, 105)
                                    .addComponent(PuertoTextField))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ColorMapaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ColorPjCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(IPlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BotonIniciarHost, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IPlabel)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PuertoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ColorMapaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ColorPjCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nicknameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BotonIniciarHost, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PuertoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuertoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuertoTextFieldActionPerformed

    private void BotonIniciarHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniciarHostActionPerformed

    private void nicknameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameTextFieldActionPerformed

 
  
    //---------------------Listeners-------------------------------------------------------
        public class IniciarHostButtonAction implements ActionListener{
            @Override
        public void actionPerformed(ActionEvent e) {
            
            puerto = Integer.parseInt(PuertoTextField.getText());
            NickName = nicknameTextField.getText();
             
            PartidaHost partida = new PartidaHost( puerto, ColorMapa, ColorPj, NickName );
            partida.inicializar();
            Thread hilo = new Thread ( partida );
            
                try { hilo.start(); }
                catch (Exception ex) { }
                
            dispose();    
        }
    } 
    public class ColorMapaComboBoxAction implements ActionListener{
            @Override
        public void actionPerformed(ActionEvent e) {
               
               String s = (String) ColorMapaCombo.getSelectedItem();
               
              switch ( s ){
                  case "Verde":{
                      ColorMapa = '1';
                      break;
                  }  
                  case "Azul":{
                      ColorMapa = '2';
                      break;
                  }
                  case "Rojo":{
                      ColorMapa = '3';
                      break;
                  }
                  case "Amarillo":{
                      ColorMapa = '4';
                      break;
                  }
              }
              
                       
        }
      } 
    
        public class ColorPjComboBoxAction implements ActionListener{
            @Override
        public void actionPerformed(ActionEvent e) {
               
               String s = (String) ColorPjCombo.getSelectedItem();
               
             switch ( s ){
                  
                  case "Blanco":{
                      ColorPj = '1';
                      break;
                  }
                  
                  case "Negro":{
                      ColorPj = '2';
                      break;
                  }    
                  case "Azul":{
                      ColorPj = '3';
                      break;
                  }
                  case "Verde":{
                      ColorPj = '4';
                      break;
                  }
                  
                  case "Rojo":{
                      ColorPj = '5';
                      break;
                  }    
                  case "Vintage":{
                      ColorPj = '6';
                      break;
                  }
              }
              
                       
        }
      } 
     
    //---------------------Listeners-------------------------------------------------------
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciarHost;
    private javax.swing.JComboBox ColorMapaCombo;
    private javax.swing.JComboBox ColorPjCombo;
    private javax.swing.JLabel IPlabel;
    private javax.swing.JTextField PuertoTextField;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nicknameTextField;
    // End of variables declaration//GEN-END:variables
}
